# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 20:32
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=50)),
                ('default_phone_number', models.CharField(blank=True, max_length=20)),
                ('default_country', models.CharField(blank=True, max_length=40)),
                ('default_postcode', models.CharField(blank=True, max_length=20)),
                ('default_town_or_city', models.CharField(blank=True, max_length=40)),
                ('default_street_address1', models.CharField(blank=True, max_length=40)),
                ('default_street_address2', models.CharField(blank=True, max_length=40)),
                ('default_county', models.CharField(blank=True, max_length=40)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
