# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 19:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 13, 19, 39, 17, 919111), verbose_name='Date'),
        ),
    ]
