# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_full_name',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 7, 13, 19, 47, 43, 466898), verbose_name='Date'),
        ),
    ]
