# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-13 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_userprofile_default_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='default_full_name',
            new_name='full_name',
        ),
    ]
