# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-20 14:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('beer', models.CharField(default='', max_length=500)),
                ('review', models.CharField(default='', max_length=2000)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='3', max_length=10)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
    ]
