# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-18 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='beer',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='item',
            name='review',
            field=models.CharField(default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
