# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-21 16:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0003_auto_20200721_1222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewlineitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
