# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-25 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0008_auto_20200723_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewlineitem',
            name='new_item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_ratings.Item'),
        ),
    ]
