# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-25 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0009_reviewlineitem_new_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewlineitem',
            name='new_item',
        ),
        migrations.RemoveField(
            model_name='reviewlineitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='ReviewLineItem',
        ),
    ]
