# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-25 11:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0011_reviewlineitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewlineitem',
            old_name='new_item',
            new_name='item',
        ),
    ]
