# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0012_auto_20200725_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlineitem',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
