# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-26 13:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0014_auto_20200726_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='product',
        ),
    ]
