# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-26 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0018_remove_item_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='user',
        ),
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
