# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-26 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0022_auto_20200726_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewlineitem',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_ratings.Item'),
        ),
        migrations.AlterField(
            model_name='reviewlineitem',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
