# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-26 18:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0023_auto_20200726_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewlineitem',
            old_name='item',
            new_name='new_item',
        ),
    ]
