# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-26 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200604_1359'),
        ('user_ratings', '0026_auto_20200726_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reviewlineitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='reviewlineitem',
            name='product',
        ),
        migrations.AlterField(
            model_name='item',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item', to='products.Product'),
        ),
        migrations.DeleteModel(
            name='ReviewLineItem',
        ),
        migrations.AddField(
            model_name='itemlineitem',
            name='item',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user_ratings.Item'),
        ),
        migrations.AddField(
            model_name='itemlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
