# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-26 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_ratings', '0028_auto_20200726_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemlineitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
