# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-29 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('description', models.CharField(default='', max_length=254)),
                ('info', models.CharField(default='', max_length=500)),
                ('blurb', models.TextField(default='')),
                ('size', models.CharField(default='', max_length=254)),
                ('alcohol', models.CharField(default='', max_length=254)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
