# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-30 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='blurb',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.CharField(default='', max_length=400),
        ),
    ]
