# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-30 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200530_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.TextField(default=''),
        ),
    ]
