# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-04 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200530_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(default=''),
        ),
    ]
