# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-04 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='alcohol',
            field=models.CharField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(default='', max_length=254),
        ),
    ]
